// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: db.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExistsUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsUserRequest) Reset() {
	*x = ExistsUserRequest{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsUserRequest) ProtoMessage() {}

func (x *ExistsUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsUserRequest.ProtoReflect.Descriptor instead.
func (*ExistsUserRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *ExistsUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ExistsUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsUserResponse) Reset() {
	*x = ExistsUserResponse{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsUserResponse) ProtoMessage() {}

func (x *ExistsUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsUserResponse.ProtoReflect.Descriptor instead.
func (*ExistsUserResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *ExistsUserResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type InsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserRequest) Reset() {
	*x = InsertUserRequest{}
	mi := &file_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserRequest) ProtoMessage() {}

func (x *InsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserRequest.ProtoReflect.Descriptor instead.
func (*InsertUserRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{2}
}

func (x *InsertUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *InsertUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type InsertUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserResponse) Reset() {
	*x = InsertUserResponse{}
	mi := &file_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserResponse) ProtoMessage() {}

func (x *InsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserResponse.ProtoReflect.Descriptor instead.
func (*InsertUserResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{3}
}

type GetUserCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCredentialsRequest) Reset() {
	*x = GetUserCredentialsRequest{}
	mi := &file_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsRequest) ProtoMessage() {}

func (x *GetUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	UserID        int32                  `protobuf:"varint,2,opt,name=user_id,json=userID,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCredentialsResponse) Reset() {
	*x = GetUserCredentialsResponse{}
	mi := &file_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCredentialsResponse) ProtoMessage() {}

func (x *GetUserCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetUserCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserCredentialsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetUserCredentialsResponse) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\x12\x05db.v1\"/\n" +
	"\x11ExistsUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\",\n" +
	"\x12ExistsUserResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"K\n" +
	"\x11InsertUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x14\n" +
	"\x12InsertUserResponse\"7\n" +
	"\x19GetUserCredentialsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Q\n" +
	"\x1aGetUserCredentialsResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userID2\xec\x01\n" +
	"\tDBService\x12A\n" +
	"\n" +
	"ExistsUser\x12\x18.db.v1.ExistsUserRequest\x1a\x19.db.v1.ExistsUserResponse\x12A\n" +
	"\n" +
	"InsertUser\x12\x18.db.v1.InsertUserRequest\x1a\x19.db.v1.InsertUserResponse\x12Y\n" +
	"\x12GetUserCredentials\x12 .db.v1.GetUserCredentialsRequest\x1a!.db.v1.GetUserCredentialsResponseB\x04Z\x02./b\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_db_proto_goTypes = []any{
	(*ExistsUserRequest)(nil),          // 0: db.v1.ExistsUserRequest
	(*ExistsUserResponse)(nil),         // 1: db.v1.ExistsUserResponse
	(*InsertUserRequest)(nil),          // 2: db.v1.InsertUserRequest
	(*InsertUserResponse)(nil),         // 3: db.v1.InsertUserResponse
	(*GetUserCredentialsRequest)(nil),  // 4: db.v1.GetUserCredentialsRequest
	(*GetUserCredentialsResponse)(nil), // 5: db.v1.GetUserCredentialsResponse
}
var file_db_proto_depIdxs = []int32{
	0, // 0: db.v1.DBService.ExistsUser:input_type -> db.v1.ExistsUserRequest
	2, // 1: db.v1.DBService.InsertUser:input_type -> db.v1.InsertUserRequest
	4, // 2: db.v1.DBService.GetUserCredentials:input_type -> db.v1.GetUserCredentialsRequest
	1, // 3: db.v1.DBService.ExistsUser:output_type -> db.v1.ExistsUserResponse
	3, // 4: db.v1.DBService.InsertUser:output_type -> db.v1.InsertUserResponse
	5, // 5: db.v1.DBService.GetUserCredentials:output_type -> db.v1.GetUserCredentialsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
