apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: gitscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: db-service
          image: gitscope/db-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: neon-db-secret
                  key: DATABASE_URL
