apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: gitscope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gitscope/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: neon-db-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: gitscope-config
                  key: JWT_SECRET
